version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    environment:
      NODE_ENV: production
      DATABASE_URL: 'postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}?schema=public'
    depends_on:
      db:
        condition: service_healthy
    restart: always

  db:
    image: postgres:13-alpine
    environment:
      POSTGRES_USER: vladislav
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: testNestjs
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U $${POSTGRES_USER}']
      interval: 5s
      timeout: 5s
      retries: 5
    restart: always

volumes:
  db_data:
